version: "3"

tasks:
  run:
    desc: Run jobit
    cmds:
      - clear
      - go run ./cmd/jobit

  seed:
    desc: Seed database
    cmds:
      - clear
      - go run ./cmd/seed
  test:
    desc: Run tests
    cmds:
      - go test ./...

